name: Generate Index

on:
  push:
    paths:
      - 'Puzzles/**.html'
      - '**_icon.PNG'  # Adjust if needed
  workflow_run:
    workflows: ["Generate Puzzle HTML"]  # This must match the name of the first workflow
    types:
      - completed  # Trigger when the first workflow is completed

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Run generate_index.py
        run: python generate_index.py

      - name: Commit and push changes
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          git config --global user.name "auto-updater"
          git config --global user.email "auto-updater@example.com"
          git remote set-url origin https://x-access-token:${PAT}@github.com/${{ github.repository }}
          git add index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update index.html"
          git push origin HEAD:main
